name: blogs workflow
on:
  schedule: # Run workflow automatically
      - cron: '0 0 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-new-blog-posts:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://feedly.com/i/subscription/feed/https://www.freecodecamp.org/news/author/farhanhasin/rss/"
